# Generated by Django 3.0 on 2019-12-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(blank=True, help_text='Longitude coordinate for squirrel sighting point')),
                ('Latitude', models.FloatField(blank=True, help_text='Latitude  coordinate for squirrel sighting point')),
                ('Unique_Squirrel_ID', models.CharField(blank=True, help_text='Identification tag for each squirrel sightings', max_length=100)),
                ('Shift', models.CharField(blank=True, choices=[('', ''), ('AM', 'AM'), ('PM', 'PM')], default='', help_text='Whether the sighting session occured in the morning or late afternoon', max_length=16)),
                ('Date', models.CharField(blank=True, help_text='Concatenation of the sighting session day and month', max_length=100)),
                ('Age', models.CharField(blank=True, choices=[('', ''), ('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='', max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('', ''), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default='', max_length=100)),
                ('Location', models.CharField(blank=True, choices=[('', ''), ('Ground Plane', 'Ground plane'), ('Above Ground', 'Above ground')], default='', help_text='the location of where the squirrel was when first sighted', max_length=100)),
                ('Specific_Location', models.CharField(blank=True, help_text="Sighters' commentary on the squirrel location", max_length=100)),
                ('Running', models.BooleanField(help_text='Whether squirrel was seen running')),
                ('Chasing', models.BooleanField(help_text='Whether squirrel was seen chasing another squirrel')),
                ('Climbing', models.BooleanField(help_text='Whether squirrel was seen climbing a tree or other environmental landmark')),
                ('Eating', models.BooleanField(help_text='Whether squirrel was seen eating')),
                ('Foraging', models.BooleanField(help_text='Whether squirrel was seen foraging for food')),
                ('Other_Activities', models.CharField(blank=True, max_length=100)),
                ('Kuks', models.BooleanField(help_text='Whether squirrel was heard kukking')),
                ('Quaas', models.BooleanField(help_text='Whether squirrel was heard quaaing')),
                ('Moans', models.BooleanField(help_text='Whether squirrel was heard moaning')),
                ('Tail_flags', models.BooleanField(help_text='Whether squirrel was seen flagging its tail')),
                ('Tail_twitches', models.BooleanField(help_text='Whether squirrel was seen twitching its tail')),
                ('Approaches', models.BooleanField(help_text='Whether squirrel was seen approaching human, seeking food')),
                ('Indifferent', models.BooleanField(help_text='Whether squirrel was indifferent to human presence')),
                ('Runs_from', models.BooleanField(help_text='Whether squirrel was seen running from humans, seeing them as a threat')),
            ],
        ),
    ]
